

#version 430



layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;



struct Particle
{
    vec4 position;
    vec4 velocity;
    vec4 attributes;
};



layout(std430, binding = 0) buffer Buf {
    Particle particles[];
};



uniform float gravMult;
uniform float timeStep;
uniform int numParticles;




void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= numParticles) return;

    vec3 pos = particles[idx].position.xyz;
    vec3 vel = particles[idx].velocity.xyz;
    float mass = particles[idx].attributes.x;

    vec3 force = vec3(0.0);
    for(int p = 0; p < numParticles; p++)
    {
        if (p == idx) continue;

        Particle particle = particles[p];

        vec3 direction = particle.position.xyz - pos;
        float dist = length(direction);

        force += direction * particle.attributes.x / (dist * dist * dist);
    }

    vec3 acceleration = gravMult * force / mass;

    pos += (timeStep * vel) + (0.5 * timeStep * timeStep * acceleration);
    vel += timeStep * acceleration;

    particles[idx].position = vec4(pos, 1.0);
    particles[idx].velocity = vec4(vel, 0.0);
}
